image:
  file: .gitpod/.gitpod.dockerfile

ports:
  - port: 8080
    onOpen: open-preview
  - port: 3306
    onOpen: ignore
  - port: 8025
    onOpen: ignore
  - port: 1025
    onOpen: ignore
  - port: 9000
    onOpen: ignore

tasks:
  - name: Some init
    command: |
      sudo rsyslogd
      sudo service mysql start
      sudo service php8.4-fpm start
      sudo service nginx start
      sudo mailhog </dev/null &>/dev/null & disown
      /bin/bash .gitpod/.init.sh
      history -c
workspaceLocation: "/var/www/html"

vscode:
  extensions:
    - usernamehw.errorlens
    # - eamodio.gitlens
    - StoilDobreff.php-resolver
    - felixfbecker.php-debug
    - neilbrayfield.php-docblocker
    - streetsidesoftware.code-spell-checker
    - TabNine.tabnine-vscode
    - sleistner.vscode-fileutils
    - bmewburn.vscode-intelephense-client
    - sdras.night-owl
    - waderyan.gitblame
    # - ms-vscode.sublime-keybindings
    - felixfbecker.php-pack
    - xdebug.php-debug
    - zaaack.markdown-editor
    - RobertOstermann.inline-parameters-extended
    - mrmlnc.vscode-duplicate

